name: ExamplePlugin
version: '${project.version}'
main: com.example.exampleplugin.Main
api-version: 1.19
authors: [ AuthorName ]
description: This is a description
website: www.example.com
commands:
  examplecommand:
    description: "ExampleCommand By Kiyoshi"
    aliases: [ excommand ]
